services:
- type: web
  name: allcode-backend
  env: python
  rootDir: backend
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
  plan: starter
  envVars:
    - key: DATABASE_URL
      fromDatabase:
        name: allcode-db
        property: connectionString
    - key: JWT_SECRET
      sync: false
    - key: ALLOWED_ORIGINS
      value: "*"
databases:
- name: allcode-db
  plan: starter
